### ISSUE TITLE
Sweetpotatobase trait formatting issue

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3362]
Expected Behavior 
--------------------------------------------------------------------------

Trait import via BrAPI in the fieldbook app (v 4.5) fails when importing traits from sweetpotatobase, but works fine for cassavabase and the brapi test server.

For Bugs:
---------

**Comment by bellerbrock** [comment]
Suggestions:
Check configuration file settings /differences.
Check trait metadata difference

**Comment by trife** [comment]
Did a little digging and I can't even get the list of traits to display off the Field Book develop branch.

```
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: empty String
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at io.swagger.client.JSON.deserialize(JSON.java:144)
        at io.swagger.client.ApiClient.deserialize(ApiClient.java:710)
        at io.swagger.client.ApiClient.handleResponse(ApiClient.java:913)
        at io.swagger.client.ApiClient$1.onResponse(ApiClient.java:879)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by bellerbrock** [comment]
Look like this is caused by empty strings in trait default cvtermprops.

**Comment by bellerbrock** [comment]
deleting all the offending cvtermprops (`begin; delete from cvtermprop where value = ' ';commit;`) solved the problem!
