### ISSUE TITLE
Upgrade Breedbase from Debian 9 to Debian 10 or 11

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3965]
Expected Behavior 
--------------------------------------------------------------------------
Debian 9 will run out of support in April 2022

For Bugs:
---------

**Comment by lukasmueller** [comment]
R packages can be updated usign the command:
update.packages(checkBuilt=TRUE, ask=FALSE)

**Comment by lukasmueller** [comment]
The above methods do not complete the upgrade process and error out.

**Comment by lukasmueller** [comment]
the docker image builds now but when I start the docker I get issues with npm. I replaced the npm install script with npm from apt. Now I get the following errors when starting the breedbase app:

818) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_LENGTH] DeprecationWarning: chunk.files was changed from Array to Set (using Array property 'length' is deprecated)
(node:9818) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_INDEXER] DeprecationWarning: chunk.files was changed from Array to Set (indexing Array is deprecated)
assets by status 4.72 KiB [cached] 7 assets
runtime modules 2.47 KiB 3 modules
modules with errors 234 bytes [errors]
  ./source/entries/boxplotter.js 39 bytes [built] [code generated] [1 error]
  ./source/entries/fieldmap.js 39 bytes [built] [code generated] [1 error]
  ./source/entries/heritability.js 39 bytes [built] [code generated] [1 error]
  ./source/entries/mixedmodels.js 39 bytes [built] [code generated] [1 error]
  ./source/entries/sequenced_accessions.js 39 bytes [built] [code generated] [1 error]
  ./source/entries/wizard.js 39 bytes [built] [code generated] [1 error]

ERROR in ./source/entries/boxplotter.js
Module build failed (from ./webpack_util/jsan-preprocess-loader.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/home/production/cxgn/sgn/js/webpack_util/jsan-preprocess-loader.js:16:30)

ERROR in ./source/entries/fieldmap.js
Module build failed (from ./webpack_util/jsan-preprocess-loader.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/home/production/cxgn/sgn/js/webpack_util/jsan-preprocess-loader.js:16:30)

ERROR in ./source/entries/heritability.js
Module build failed (from ./webpack_util/jsan-preprocess-loader.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/home/production/cxgn/sgn/js/webpack_util/jsan-preprocess-loader.js:16:30)

ERROR in ./source/entries/mixedmodels.js
Module build failed (from ./webpack_util/jsan-preprocess-loader.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/home/production/cxgn/sgn/js/webpack_util/jsan-preprocess-loader.js:16:30)

ERROR in ./source/entries/sequenced_accessions.js
Module build failed (from ./webpack_util/jsan-preprocess-loader.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/home/production/cxgn/sgn/js/webpack_util/jsan-preprocess-loader.js:16:30)

ERROR in ./source/entries/wizard.js
Module build failed (from ./webpack_util/jsan-preprocess-loader.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/home/production/cxgn/sgn/js/webpack_util/jsan-preprocess-loader.js:16:30)

webpack 5.70.0 compiled with 6 errors in 704 ms
npm ERR! code 1
npm ERR! path /home/production/cxgn/sgn/js
npm ERR! command failed
npm ERR! command sh -c npm run reset && webpack --config build.webpack.config.js

**Comment by lukasmueller** [comment]
Because many Perl dependencies are install from apt in the docker, they are not available in the perl local-lib git repo anymore. Use this command line to install the missing libraries.

aptitude install -y npm libterm-readline-zoid-perl nginx starman emacs gedit vim less sudo htop git dkms  perl-doc ack make xutils-dev nfs-common lynx xvfb ncbi-blast+ libmunge-dev libmunge2 munge slurm-wlm slurmctld slurmd libslurm-perl libssl-dev graphviz lsof imagemagick mrbayes muscle bowtie bowtie2 postfix mailutils libcupsimage2 postgresql-client-12 libglib2.0-dev libglib2.0-bin screen apt-transport-https libgdal-dev libproj-dev libudunits2-dev locales locales-all rsyslog cron  libnlopt0 libcatalyst-controller-html-formfu-perl libmoosex-runnable-perl

**Comment by lukasmueller** [comment]
To get slurm working, move the ```/etc/slurm-llnlslurm.conf``` file to ```/etc/slurm/```

Also, add 
SelectType=select/cons_res
SelectTypeParameters=CR_CORE

Remove the option
FastSchedule=1
if present

**Comment by lukasmueller** [comment]
apt install linux-image-5.10.0-13-amd64 (or similar version - must match version in /etc/xen/...cfg file) in case the files in /boot went missing

**Comment by lukasmueller** [comment]
To get npm to work, the following commands may have to be run on a vm:
```
rm -Rf js/node_modules
rm -Rf ~/.npm
rm /usr/local/bin/npm   # manually installed npm from old OS versions
rm /usr/local/bin/node  # same

```

**Comment by lukasmueller** [comment]
Note: sometimes ```$PERL5LIB``` needs to be unset, as in ``` unset PERL5LIB ```.
Also, the contents of ```$PERL5LIB``` may have to be adjusted on older servers.

**Comment by lukasmueller** [comment]
ALWAYS use screen to run an upgrade:
```
sudo screen apt upgrade
```
so that nothing bad happens when an ssh connection hangs.

**Comment by lukasmueller** [comment]
To start docker-compose on boot using systemd on the host, create a systemd service file with the following contents:
```
[Unit]
Description=Starts the Breedbase docker-compose server

[Service]
ExecStart=/home/production/docker/breedbase_docker.sh

[Install]
WantedBy=multi-user.target
```
the breedbase_docker.sh file contains:
```
#!/bin/bash

export HOME=/home/production

echo "cd into docker dir...";
cd /home/production/docker;

echo "start docker-compose..."
docker-compose up -d;

echo "done."
```

**Comment by lukasmueller** [comment]
Another note: Some systems upgraded from Debian 9 to 10 to 11 seem to have problem with network connectivity. Network drops after a few seconds after turning it on. The only way to fix this is to do a fresh install of the operating system... :-(

**Comment by lukasmueller** [comment]
For systems that run docker, if after the host upgrade docker refuses to run, with an error message such as
```
docker.service: Failed with result 'exit-code'.
```
try the following:
```
rm -Rf /var/log/docker/aufs
```
Be careful not to blow away the entire docker dir...

**Comment by lukasmueller** [comment]
for Debian 11, the only way more loop devices could be generated was to put the word ```loop``` in the file ```/etc/modules``` and create a file called ```/etc/modprobe.d/etc-modules-parameters.conf``` with the contents: 
``` options loop max_loop=64 ```

**Comment by lukasmueller** [comment]
default ```/etc/apt/sources.list``` file for vms and hosts:
```
deb http://deb.debian.org/debian bullseye main contrib non-free
deb-src http://deb.debian.org/debian bullseye main contrib non-free

deb http://deb.debian.org/debian-security bullseye/updates main contrib non-free
deb-src http://deb.debian.org/debian-security bullseye/updates main contrib non-free

deb http://deb.debian.org/debian bullseye-updates main contrib non-free
deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

deb http://deb.debian.org/debian bullseye-backports main contrib non-free
deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free
```

**Comment by lukasmueller** [comment]
All Breedbase servers and VMs have been updated! :-)
