### ISSUE TITLE
Problems building npm dependencies in jbrowse

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4312]
Expected Behavior 
--------------------------------------------------------------------------
Running the setup.sh script in the jbrowse directory gives the following error:

Error: Dojo loader version does not match the version of Dojo.
Loader version = 1.16.2.
Dojo version = 1.17.3.
You may need to rebuild the Dojo loader.
Refer to https://github.com/OpenNTF/dojo-webpack-plugin/blob/master/README.md#building-the-dojo-loader
    at /export/prod/jbrowse-common/jbrowse/node_modules/dojo-webpack-plugin/lib/DojoLoaderValidatorPlugin.js:55:13
    at /export/prod/jbrowse-common/jbrowse/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /export/prod/jbrowse-common/jbrowse/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at _next0 (eval at create (/export/prod/jbrowse-common/jbrowse/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:77:1)
    at eval (eval at create (/export/prod/jbrowse-common/jbrowse/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:93:1)
    at DojoAMDModuleFactoryPlugin.afterResolve (/export/prod/jbrowse-common/jbrowse/node_modules/dojo-webpack-plugin/lib/DojoAMDModuleFactoryPlugin.js:311:3)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/export/prod/jbrowse-common/jbrowse/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:86:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/export/prod/jbrowse-common/jbrowse/node_modules/tapable/lib/Hook.js:154:20)
    at /export/prod/jbrowse-common/jbrowse/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /export/prod/jbrowse-common/jbrowse/node_modules/dojo-webpack-plugin/lib/DojoAMDModuleFactoryPlugin.js:330:5
    at /export/prod/jbrowse-common/jbrowse/node_modules/webpack/lib/NormalModuleFactory.js:346:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

For Bugs:
---------

**Comment by lukasmueller** [comment]
Solution:

move the node_modules directory to node_modules_old
move the package-lock.json module to package-lock.json_old
edit the package.json file and change the version of the following dependencies to:
   "dojo": "1.16.2",
   "dojo-util": "1.16.2",

However, all this should not be necessary... what is wrong here???
